// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// solve_sylvester_real
arma::mat solve_sylvester_real(const arma::mat& A, const arma::mat& B, const arma::mat& Q);
RcppExport SEXP _sylvester_solve_sylvester_real(SEXP ASEXP, SEXP BSEXP, SEXP QSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Q(QSEXP);
    rcpp_result_gen = Rcpp::wrap(solve_sylvester_real(A, B, Q));
    return rcpp_result_gen;
END_RCPP
}
// solve_sylvester_cplx
arma::cx_mat solve_sylvester_cplx(const arma::cx_mat& A, const arma::cx_mat& B, const arma::cx_mat& Q);
RcppExport SEXP _sylvester_solve_sylvester_cplx(SEXP ASEXP, SEXP BSEXP, SEXP QSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cx_mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::cx_mat& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const arma::cx_mat& >::type Q(QSEXP);
    rcpp_result_gen = Rcpp::wrap(solve_sylvester_cplx(A, B, Q));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sylvester_solve_sylvester_real", (DL_FUNC) &_sylvester_solve_sylvester_real, 3},
    {"_sylvester_solve_sylvester_cplx", (DL_FUNC) &_sylvester_solve_sylvester_cplx, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_sylvester(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
