# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

solve_sylvester_real <- function(A, B, Q) {
    .Call(`_sylvester_solve_sylvester_real`, A, B, Q)
}

solve_sylvester_cplx <- function(A, B, Q) {
    .Call(`_sylvester_solve_sylvester_cplx`, A, B, Q)
}

